github:
  user_or_org: Emblanc
travis:
  secure:
    BINSTAR_TOKEN: h2nTjyvNeo926hy4Ncjt0OwMk+4cH6/SoYTDvY2BziN1w7SfdoTU/c+ct5TGdFb84+04+sfSDH2frpueUV+/dwG19bte0IkyjAZa0Uev4k+MXy5w5O4RHQ3LkZ2y8M9MnvnYobbet72/iCEDnHBeKar29L2pt4SCfhGs3fLASJy6tvxey4KCqYv5Muu4IoOIpzl1XyNSkuYa7V3Zf+B6jJJWoDHiVHvdTplzRfiP2b5YQacBVycgrDq1jOVtEeUHAgtXvTFs5TXZ7rm0T4/NBu8ZVWgp/8HAbJtfqBfNONWNnXqyujhhNV7aZAKtWy5qvz+og2TVjCXnGrSYee8HchAhiqd7Vl+3eVQn1rXS1SYSqaJbuHEHbG1undZ14d5ckEo4ruUd+kzhW0ME1YR6OHXeclVgiTN+YLpCoUe5cYFDtGUAH1wOnBSlmhQLnJcRfDC8jOFi3XN6zTc7iXuYYHKSBNRlESXrp9nqc2CqNNgwmmy2Dt7e/7zgDNy73p76g23IMbmH2Mixe9yYUK+p9c8l51K4tX+73h5EptU8afGUI3gvfZcA3QJb79Nr4PcX2nXAZg6oAD8M6e4dH3Cl4x0EhbPXPT+BjdOZdT9RyurffbpPQPQA8n2mObdnBn7ereIibEdDE0wnFDF4mba4jq1GkjWx/PE0K83GxgaL5eA=
appveyor:
  secure:
    BINSTAR_TOKEN: HbSE6MzzY0NxHW7Os5UZ907ZUKZ98OFs2nvopJGM9cg=
