github:
  user_or_org: Emblanc
travis:
  secure:
    BINSTAR_TOKEN: 9kaTxei9mVg7Mh8UtDRxmrWToqaAUA+Ni1dTtxZCq3Th5DbTkO1ZYYkHTwAPHOITUmZe1Jprhfx6daJ04myyEtRZesdOoTfTzRT8GUuMR15NC4QChtZeqW5qqdNmU9AcN8mRW7lqpuwsDEwEYmgtsJ8cE/af0r3Iy98AUAXqr6bV5sM44Mx+8XQPfRquf6iSYZ+p8CIQU+mItmhLMjMbt7UITMbv85nPjEXmREBG2eKKce07TzkPOu3hqxky8E559y/2aUkhiMLVGG1VJz+eOjpfmTUkhKKAWAHinkcgEddebTLxHkRPTy4uzLfT9tUizvIqQWkzkgX9FDySw2HlrSZdudEReQsQbGNrmI4sn0tweLsVyxz9GuPupI8+J7gU65mlizEBO0lwBKwhH1lsnyMesD7fq0Eksb7XhWQWqUGoCyCc8r1UTyVWSL4kaOPNobdblHZfYM/qafqaBX2rKAOx4wBL0fezCQDxcp4Vg7E4kCCXkWUjN7doUc8gqtURKqlh23C9wA4fiS27RkgC1iwSSHwDanZPUNJUeuSKIz7DybWjrbCCrho/wxVlu/muKEFILZc0vGJJO0S3aVmP0UeO1v3tBAEDHwzoMP0gL2gBVmEGPpydy2q7xAvLH7d+GiGMWkajsBI/JF6vzQ2CKxfI/xD2+88fLHbxbqBOC44=
appveyor:
  secure:
    BINSTAR_TOKEN: HbSE6MzzY0NxHW7Os5UZ907ZUKZ98OFs2nvopJGM9cg=
