github:
  user_or_org: Emblanc
travis:
  secure:
    BINSTAR_TOKEN: SHEwkDHHhLP1Wn7J79ipWNC304xxDebALjCVEzDgicREU63KHlZLSzJXEB5v6Dm1DnqbuEzH/xhOvxRDq0X+RqwIJr1QahTNzTAzGttvMhDwdbIyMkRI9rYTDVGI8sIF2JUGlqQJOqGSXMkAR9H2Ek+Lyts543lrgU4Noava6TGCUmqLs6xp39sGdFky1ltVxJELENSChEa5Qt13Z0mLEXYT3weEtxz8RF9l2YUYsCK90csczcX5sRWImW+vIQBG7MS70lJOQYRkb2T3RSdEqZV4Y+WKpzuEed6Uy3eus0rDdd4oXvB7L2YFNPgpeWggmjJCEhdHb56++1s023y+bMzpvAL0M4x1fO5C7VmWFTBacVlFChKCoznzknjdcfLzE9nhLyu63IIBaABQU6YE4rllcBXnU51g/jhcFhX5ySi9LAp368Ghpp6bQMFdlDUZqmFJDqjm/bCHsyXfuPMfoCfmgCY0lvj7d7fbWY2l8dFQOib9YiYkcolgELUTqHRcws1HcebJrn5jA2J5D+YqYNVyS8YuVH4mCCXcTmNBsQKSA1YQ6KrWGYCKzLFMWT50UcmpfxZ46Y5xItO/XdSsPa6VOBn4Zd/3hA82y4qZpolVWxrtndYeLvjscgTQg+IHmCFsT/iHCsbu+DC5YZgs+pKE/zq6bvruN9PzB4nVV/0=
appveyor:
  secure:
    BINSTAR_TOKEN: HbSE6MzzY0NxHW7Os5UZ907ZUKZ98OFs2nvopJGM9cg=
