github:
  user_or_org: Emblanc
travis:
  secure:
    BINSTAR_TOKEN: UtnvFDMjBoGPq4OxbzHtMJzpAnpGFTyV19ETXNsTfoMopvAdcfMz1vItLxWlIcSnWWy+GynadUWEGb//09dpQ5OMI+aKgBIpRDvhs5NRwpV1+JYnQq+V0xluJNyF9CMtKgJdMjggJd3LkeDrkyd16xlqw53ytNLkh9nUKNZQrwjRrQ4uLz7MjkG16OBsgmIehNZBTOxGnG9PgWczv5V5n9f0UkL3cZt0x2ys0BcHddDuPrERajtdQ9SEtHSF4Om2T6IYfx5qM8+tx6Ouend0np5phcFZjRGtzAT9X7PU2P6YCoKOxQ45rvJ2exS+sniwOT+WrtYYXQ+OqcwQ2uTm+2a/2QqH5ZUeRLC0rJrvdjA16KLCLarMxTVr9fxdrxNL6HSeVSligiXzjZ660RrFKuHEEUGYUhUebGjq65jZMLHeTwEyksReBHpgcq+1W40alrP7UAg00AC5udEDT6a8fnPIW7MdBGDiiisCq5FJ9gjzcOx9FxtCK5UPbF2chM8FRfghEPRNS1zhildqcY07YODTrWHloSdj92ommG1IejDa3cir0ObpbzkerDRhmlpcux7WnYptkyXdZFA28Zo87TaeEfTjFnL9VP0VJITD2e8L54Tpgfc+tiUcSn406rRZwjD1/mqIvXWvoyhnPF/+25CHSpUoc5wbAA+UTlpQRCY=
appveyor:
  secure:
    BINSTAR_TOKEN: ClVeSaYOwAC81DrBN7y1vvGX+rNkCTDugFHDNClU8TaPNs/uS/mhYt5IkSFP6ZZD
